# Generated by Django 5.0.14 on 2026-06-12 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('start', 'Start'), ('comfort', 'Komfort'), ('cargo', 'Yuk taksi')], max_length=10, unique=True, verbose_name='Kategoriya')),
                ('base_fare', models.PositiveIntegerField(help_text='S_chaqiruv -- taksi chaqirilishi uchun doimiy tolov', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Boshlangich narx (som)')),
                ('per_km', models.PositiveIntegerField(help_text='S_km -- har kilometr uchun tolov', validators=[django.core.validators.MinValueValidator(1)], verbose_name='1 km narxi (som)')),
                ('rush_fee_low', models.PositiveIntegerField(default=3000, help_text='Oddiy shoshilinch ustama', verbose_name='Shoshilinch kam ustama (som)')),
                ('rush_fee_high', models.PositiveIntegerField(default=5000, help_text='Yuqori shoshilinch ustama', verbose_name='Shoshilinch yuqori ustama (som)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
                'ordering': ['category'],
            },
        ),
    ]
