# Generated by Django 5.0.14 on 2026-06-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum')], max_length=10)),
                ('amount', models.PositiveIntegerField(verbose_name='Miqdor (som)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=12)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('raw_payload', models.JSONField(default=dict, help_text='Webhook dan kelgan toliq JSON', verbose_name='Xom malumot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Tolov sorovi',
                'verbose_name_plural': 'Tolov sorovlari',
                'indexes': [models.Index(fields=['external_id'], name='payments_pa_externa_8f85ac_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_4b97d4_idx')],
            },
        ),
    ]
