# Generated by Django 5.0.14 on 2026-06-12 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('start', 'Start'), ('comfort', 'Komfort'), ('cargo', 'Yuk taksi')], max_length=10, verbose_name='Mashina turi')),
                ('car_number', models.CharField(max_length=10, unique=True, verbose_name='Davlat raqami')),
                ('car_model', models.CharField(blank=True, max_length=50, verbose_name='Mashina modeli')),
                ('is_active', models.BooleanField(default=False, help_text='Balans < 5000 som bolsa False ga tushiriladi', verbose_name='Aktiv (buyurtma olishi mumkin)')),
                ('is_online', models.BooleanField(default=False, verbose_name='Onlayn')),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('card_token', models.CharField(blank=True, help_text='Anorbank yoki Payme Epos tokenized karta', max_length=255, verbose_name='Karta tokeni')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
                'indexes': [models.Index(fields=['is_active', 'is_online', 'car_type'], name='drivers_dri_is_acti_537625_idx')],
            },
        ),
    ]
