# Generated by Django 5.0.14 on 2026-06-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Balans (som)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Hamyon',
                'verbose_name_plural': 'Hamyonlar',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Musbat = kirim, manfiy = chiqim', verbose_name='Miqdor (som)')),
                ('tx_type', models.CharField(choices=[('topup', 'Toldirish'), ('commission', 'Komissiya yechish'), ('refund', 'Qaytarish'), ('cashback', 'Cashback')], max_length=12, verbose_name='Tur')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum'), ('manual', 'Qolda')], default='manual', max_length=10, verbose_name='Tolov tizimi')),
                ('external_tx_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('balance_after', models.IntegerField(default=0, verbose_name='Operatsiyadan keyingi balans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__a053af_idx'), models.Index(fields=['external_tx_id'], name='wallet_tran_externa_229c14_idx')],
            },
        ),
    ]
