# Generated by Django 5.0.14 on 2026-06-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.FloatField(default=0, help_text='GPS spoofing aniqlash uchun', verbose_name='Tezlik (km/s)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Haydovchi joylashuvi',
                'verbose_name_plural': 'Haydovchilar joylashuvi',
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='drivers.driver')),
                ('order', models.ForeignKey(blank=True, help_text='Buyurtma davomidagi koordinata', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'verbose_name': 'Joylashuv tarixi',
                'verbose_name_plural': 'Joylashuv tarixi',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', 'timestamp'], name='locations_l_driver__643152_idx')],
            },
        ),
    ]
