# Generated by Django 5.0.14 on 2026-06-12 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=255, verbose_name='Qayerdan')),
                ('to_address', models.CharField(blank=True, max_length=255, verbose_name='Qayerga')),
                ('from_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('from_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('to_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('car_type', models.CharField(choices=[('start', 'Start'), ('comfort', 'Komfort'), ('cargo', 'Yuk taksi')], max_length=10, verbose_name='Mashina turi')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('arrived', 'Haydovchi keldi'), ('started', 'Yolda'), ('done', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='new', max_length=12, verbose_name='Holat')),
                ('base_fare', models.PositiveIntegerField(default=0, verbose_name='Boshlangich narx')),
                ('distance_km', models.FloatField(default=0, verbose_name='Masofa (km)')),
                ('rush_fee', models.PositiveIntegerField(default=0, verbose_name='Shoshilinch ustama')),
                ('total_fare', models.PositiveIntegerField(default=0, verbose_name='Jami narx')),
                ('commission', models.PositiveIntegerField(default=0, verbose_name='Komissiya (10%)')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('qr', 'QR (Click/Payme/Uzum)')], default='cash', max_length=10, verbose_name='Tolov turi')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Tolangan')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Shoshilinch')),
                ('used_saved_address', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to='drivers.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'), models.Index(fields=['driver', 'status'], name='orders_orde_driver__83706f_idx'), models.Index(fields=['client', 'created_at'], name='orders_orde_client__8a22e4_idx')],
            },
        ),
    ]
